# Wrangler configuration for CareTrack
name = "caretrack"
compatibility_date = "2024-12-06"

# Pages configuration - this tells Wrangler it's a Pages project
pages_build_output_dir = "dist"

# SPA routing - redirect all routes to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200